### ISSUE TITLE
Application Insights with kubernetes on AKS is not sending the data to AppInsights

### ISSUE THREAD

**Issue by rgovardhms** [Microsoft/ApplicationInsights-Kubernetes#92] opened 2018-02-22 10:37 UTC
Hello,

I have followed the documentation https://github.com/Microsoft/ApplicationInsights-Kubernetes/wiki/Hosting-startup-for-ApplicationInsights.Kubernetes for configuring AI on K8S but I couldn't see any data being pushed to AppInsights. How do we go about debugging the issue.

**Comment by rgovardhms** [comment] 2018-02-23 11:04
I have followed the documentation in the advanced section on how to do self diagnostics. But couldnt get useful information.
Also what is the right value to be used in the deployment.yaml file for ASPNETCORE_HOSTINGSTARTUPASSEMBLIES ? Is it Microsoft.ApplicationInsights.Kubernetes or Microsoft.ApplicationInsights.Kubernetes.HostingStartup ?

**Comment by khushalpatel1981** [comment] 2018-02-23 12:47
Hello @rgovardhms  We are running Application Insights successfully with kubernetes on ACS using 
 
services.EnableKubernetes();

Please check the following doc

ref : https://github.com/Microsoft/ApplicationInsights-Kubernetes/wiki/Getting-Started-for-ASP.NET-Core-Applications

**Comment by rgovardhms** [comment] 2018-02-23 13:05
Thanks @khushalpatel1981 . I can try that as well. But is there any issue with Hosting startup for AI approach? We have planning scenario for which it would be great if the approach I am interested in would work.

**Comment by xiaomi7732** [comment] 2018-02-23 19:24
@rgovardhms Thanks for the feedback. Please use:
```
ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=Microsoft.ApplicationInsights.Kubernetes.HostingStartup
```
It was a mistake in the document and I've updated the document. Feel free to reply back if that is still not working.

**Comment by rgovardhms** [comment] 2018-02-26 14:16
Is it possible to have a chat? You can ping me on microsoft alias - when you search for "Ranganath G"

**Comment by xiaomi7732** [comment] 2018-02-27 20:02
We trouble shot the issue offline. The issue is the application insights key is not set due to lack of the information in the documentation.
The issue is resolved and we see the result in @rgovardhms's project with the startup-host.
The document has been updated to notice the step as well.

I'll close this issue. Feel free to re-open if more follow up is needed.

**Closed by xiaomi7732** 2018-02-27 20:02 UTC
Labels: troubleshoot
