### ISSUE TITLE
Not compatible with cgroupv2

### ISSUE THREAD

**Issue by pkoelbl** [microsoft/ApplicationInsights-Kubernetes#246] opened 2021-12-22 16:22 UTC
This is not compatible with cgroupv2 and causes an error when initializing Application Insights Kubernetes
KubeHttpClientSettingsProvider.cs line 25 string pathToCGroup = @"/proc/self/cgroup" 

See this for details
https://stackoverflow.com/questions/68816329/how-to-get-docker-container-id-from-within-the-container-with-cgroup-v2

**Comment by xiaomi7732** [comment] 2022-01-21 22:02
Hi @pkoelbl Thanks for the reporting.

I tried it on docker 20.10.10 with the latest alpine and it appears still working:

![image](https://user-images.githubusercontent.com/3674549/150605969-75ef222f-f3d9-4512-82fd-c3c657797787.png)

Is there anything else needed to reproduce the issue? Thanks!

**Comment by pkoelbl** [comment] 2022-02-15 14:44
I am on a Mac using Docker Desktop 4.4.2(73395) Docker engine 20.10.12 with Kubernetes 1.22.5 enabled. Using kubernetes to create the pod. Using mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim as the base image. When i connect to the pod and look at the cgroup file it is empty.

**Comment by pkoelbl** [comment] 2022-02-15 14:55
The app is also running as a non-root user.

**Comment by xiaomi7732** [comment] 2022-02-15 18:51
@pkoelbl Thanks for the update. We will look into that.

**Comment by xiaomi7732** [comment] 2022-02-15 18:57
@pkoelbl I updated the env (Docker Desktop: 4.5.1, Engine: 20.10.12, K8s:1.22.5), am still able to access cgroups:

```shell
PS D:\> docker run -it mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim
root@ca7739f0a9f1:/# cat /proc/self/cgroup
14:name=systemd:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
13:rdma:/
12:pids:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
11:hugetlb:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
10:net_prio:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
9:perf_event:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
8:net_cls:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
7:freezer:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
6:devices:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
5:blkio:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
4:cpuacct:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
3:cpu:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
2:cpuset:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
1:memory:/docker/ca7739f0a9f1ab77959378e36b48c22d68410adae6db2e44be7b04271e49a81c
0::/
root@ca7739f0a9f1:/# exit
exit
```

Yes, I am running as root there, and that makes me think, maybe the problem is not about cgroup, it is about permission. Do you mind run the same command in your environment just to see what if you have `root`?

```shell
docker pull mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim
docker run -it mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim

/# cat /proc/self/cgroup
```

**Comment by pkoelbl** [comment] 2022-02-15 20:40
When running that I get
`root@c70c50bfc108:/# cat /proc/self/cgroup   
0::/
root@c70c50bfc108:/# `

**Comment by pkoelbl** [comment] 2022-02-15 20:50
This started happening when I did a clean install of docker after reloading my Mac. So it may be a matter of a setting that isn't there anymore in docker 20.10.12 but would be left over from an upgrade from a previous version

**Comment by pkoelbl** [comment] 2022-02-15 22:07
In the file `~/Library/Group\ Containers/group.com.docker/settings.json`
I set `deprecatedCgroupv1` to true then restarted docker and it fixed the problem.

However given the name of that variable, it looks like Docker is in the process of deprecating cgroup v1. So this will become a problem again in the future.

**Comment by xiaomi7732** [comment] 2022-02-16 18:32
@pkoelbl Thank you for figuring that out. You point about deprecating cgroupv1 is well taken. We will need to understand how to make it work with cgroupv2 or find out some other ways to get the same information. I will keep this issue active until we have a solution.

**Comment by xiaomi7732** [comment] 2022-02-16 18:34
Also, clues are welcome about how to fetch the container id alternatively. Please comment!

**Comment by xiaomi7732** [comment] 2022-03-25 22:44
NuGet package: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/2.0.3-beta1

**Comment by xiaomi7732** [comment] 2022-05-26 22:25
That wasn't the right fix.

I didn't realize `cgroupv2` is blocking accessing container id totally. The impact is bigger than expected:

* **ContainerID** can't be fetched through cgroup anymore. There doesn't seem like a stable work-around either;
* **ContainerName** won't be fetched if container can't be located inside a pod;

I am re-open this issue for investigation.

**Comment by xiaomi7732** [comment] 2022-05-26 22:37
By searching, maybe `/proc/self/mountinfo` is a place to fetch the container id:

```shell
cat /proc/self/mountinfo

678 655 254:1 /docker/containers/7a0144cee1256c539fab790199527b7051aff1b603ebcf7ed3fd436440ef3b3a/resolv.conf /etc/resolv.conf rw,relatime - ext4 /dev/vda1 rw
679 655 254:1 /docker/containers/7a0144cee1256c539fab790199527b7051aff1b603ebcf7ed3fd436440ef3b3a/hostname /etc/hostname rw,relatime - ext4 /dev/vda1 rw
680 655 254:1 /docker/containers/7a0144cee1256c539fab790199527b7051aff1b603ebcf7ed3fd436440ef3b3a/hosts /etc/hosts rw,relatime - ext4 /dev/vda1 rw
```

**Comment by pkoelbl** [comment] 2022-05-27 21:24
yes the mountinfo should do the trick

**Comment by xiaomi7732** [comment] 2022-06-06 18:35
@pkoelbl Hey, the fix is released in https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/2.0.4-beta2. Give it a try and let us know. Thanks for the contribution. I'll close this issue for now. Feel free to re-open or file new ones.

**Closed by xiaomi7732** 2022-06-06 18:35 UTC
Labels: status:resolved
