### ISSUE TITLE
Upgrade of `KubernetesClient` dependency

### ISSUE THREAD

**Issue by tomachristian** [microsoft/ApplicationInsights-Kubernetes#357] opened 2024-01-09 09:02 UTC
**Is your feature request related to a problem? Please describe.**
We are using `Microsoft.Orleans.Hosting.Kubernetes 8.0.0` which uses `KubernetesClient (>= 12.1.1)` whilst latest `Microsoft.ApplicationInsights.Kubernetes 6.1.1` is using `KubernetesClient (>= 10.0.16 && < 11.0.0)`. For this reason we cannot use them together. Any plans to upgrade the `KubernetesClient` dependency?

**Describe the solution you'd like**
That the `KubernetesClient` be upgraded to the latest version.

**Describe alternatives you've considered**
We couldn't find any besides dropping this library completely.

**Comment by tomachristian** [comment] 2024-01-29 07:32
@xiaomi7732 any timeline on when these changes will be released?

**Comment by xiaomi7732** [comment] 2024-01-30 01:30
Hey @tomachristian I will work on a beta package for testing in a couple of days. Will that work for you?

**Comment by xiaomi7732** [comment] 2024-01-30 01:59
Please check this one: https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/6.1.2-beta1

**Comment by nZeus** [comment] 2024-01-30 08:12
Thank you @xiaomi7732 ! 👍

**Comment by dsempi** [comment] 2024-03-20 13:32
@xiaomi7732: Can we reopen the issue? There were breaking changes between KubernetesClient 10 and 11. Specifically, `KubernetesClient.Models` and `KubernetesClient.Basic` are no longer separate and are now part of the `KubernetesClient` assembly itself. Could we please have a version that references the newer version of the `KubernetesClient` assembly? Thank you!

**Comment by xiaomi7732** [comment] 2024-03-21 16:54
@dsempi, thanks for sharing the details. That's kind of issue that would happen upon losing the dependencies. I could bump up the client to use K8sClient 11 or even 12, but there's still potential problems for 13 and 14 in the future.
It looks like we will have to have a strategy to depend on various versions.

One way is to sim-ship multiple versions, the problem is that it will greatly increase the maintains cost.

Maybe a way out is to ship a major version that maps to the k8s client major versions, and then, keep up with the latest?

For example, the current 2.x will keep using 10.x; and then, release a 11.0 to use 11; release a 12.0 to use 12; release a 13.0 to use 13. Moving forward, we will update the dependencies gradually only for 13. And hopefully, when 14 releases, we will be ready to move on to use 14 already? Will that work?

What do we think will be a good version to dependent on at this point?

**Comment by dsempi** [comment] 2024-03-22 07:12
The versioning strategy, wherein KubernetesClient versions are mapped to ApplicationInsights.Kubernetes versions, appears feasible. However, there's a notable drawback: users who must stick with an older KubernetesClient version may miss out on the latest features/fixes of ApplicationInsights.Kubernetes.
Upon examining the usage of KubernetesClient within the ApplicationInsights.Kubernetes codebase, it's evident that the dependency isn't overly tight. Consequently, the impact of a breaking change in KubernetesClient (as occurred between versions 10 and 11) is relatively low.
A proposed versioning approach could be as follows: Version 6.1.1 remains dependent on KubernetesClient versions <10, 11). Subsequently, a version 6.2.0 could be produced, which would support KubernetesClient versions <11, 14).
Upon the release of a new KubernetesClient version 14, compatibility checks can be conducted. If the compatibility is confirmed, Version 6.2.1 could be created, with support for KubernetesClient versions <11, 15). If not, Version 6.3.0 could be developed, with support for KubernetesClient <14, 15).
This approach aims to balance maintenance, compatibility and access to the latest features/fixes for users of ApplicationInsights.Kubernetes. What are your thoughts on this strategy?

**Comment by xiaomi7732** [comment] 2024-03-22 17:54
@dsempi Yes, there's going to be drawback for existing users. And I think you observed it correct that we don't have an over tight dependency on K8s client. I like your proposal, it looks like a balanced compromise. But I want to explorer a little bit on @samuelcadieux idea as well.

@samuelcadieux firstly, could you please file the other issue separately? With regarding the versioning, will your approach require reference to multiple versions of K8sClient at the same time? Is there any known project uses something like that? Or do I misunderstand your proposal?

**Comment by xiaomi7732** [comment] 2024-03-23 23:44
Add a bit background for a project to reference multiple versions of the same NuGet package, it doesn't seem the mechanism would just work: https://github.com/NuGet/Home/issues/12400

**Comment by xiaomi7732** [comment] 2024-03-24 00:27
More investigation result:
The current code will keep working until K8sClient.12.0.16. It will start to break for versions above 12.1.1.

The current consideration is to split the versions like this:

| Application Insights Kubernetes | Kubernetes Client | Remarks                                     |
|---------------------------------|-------------------|---------------------------------------------|
| 6.1.3                           | [10.0.16, 12.1.0) | No feature work                             |
| 6.2.0                           | >=12.1.1          | Until another compatibility issue shows up. |

I'll still need to verify that there's no break change >= 12.1.1.

**Comment by xiaomi7732** [comment] 2024-03-24 00:50
- For 6.1.3 release: https://github.com/microsoft/ApplicationInsights-Kubernetes/pull/362
- For 7.x release / develop: https://github.com/microsoft/ApplicationInsights-Kubernetes/pull/363

**Comment by xiaomi7732** [comment] 2024-03-25 17:38
I am about to move forward with those PRs, any push back? Thanks!

**Comment by dsempi** [comment] 2024-03-26 07:34
@xiaomi7732: Looks good to me. Could we get the release of 7.0.0 in the same time as 6.1.3?

**Comment by xiaomi7732** [comment] 2024-03-26 21:54
@dsempi That's exactly what I am planning to do. I am also figuring out where to put the information about which version to pick for the end user.

**Comment by dsempi** [comment] 2024-03-27 09:57
@xiaomi7732: I guess, a small note in README.md should be sufficient. The NuGet itself will have different version of KubernetesClient as a dependency, so a consumer should know which one to pick.

**Comment by xiaomi7732** [comment] 2024-03-28 21:33
Please find out the beta packages:
* https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/6.1.3-beta1
* https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/7.0.0-beta1

**Comment by xiaomi7732** [comment] 2024-06-06 22:50
Stable versions released:
* <https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/6.1.3>
* <https://www.nuget.org/packages/Microsoft.ApplicationInsights.Kubernetes/7.0.0>
I'll close this issue. Feel free to file new ones if there's other problem.

**Closed** 2024-06-06 22:50 UTC
Labels: status:resolved, discussion
