### ISSUE TITLE
No insight output as indicated in Zero Code light up Example

### ISSUE THREAD

**Issue by eliassal** [microsoft/ApplicationInsights-Kubernetes#340] opened 2023-02-13 14:36 UTC
I followed instructions at Zero Code light up Example, deployed the app to Local kubernetes (with docker desktop), I can access the url and right message is displayed as follows

![image](https://user-images.githubusercontent.com/8447864/218485971-3be0e278-0a3c-4e94-9d05-74e9ea7babd7.png)

Indicated at the end (after a while 2 minutes) that I should see output for Insights details which is not the case. I waited for more than 15 minutes and nothing happened.

So regarding the RBAC created, not sur I understand how it will get permissions in Azure? does deploy the sarole.yml would create the RBAC and grant permissions? to what knowing that the cluster is local not in Azure, it is a little bit confusing

Thanks for your help

**Comment by xiaomi7732** [comment] 2023-02-13 18:16
Hi @eliassal
I see your other issue (#339), and putting it together with this one, I kind of know where the confusion is.

Now, I am not a K8s cluster expert, but here's my understanding: `kubectl` is contextual, which means it could work for both local and remote clusters (multiple clusters). Please refer to [Connect to the cluster](https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-cli#connect-to-the-cluster) to see how to connect kubectl to your AKS cluster.

And to fully understand how kubectl works with multiple clusters, refer to this k8s official documentation: [Configure Access Multiple Cluster](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/).

The 2nd issue that I see, is that the zero code light-up example is not working. I'll take a look at what is going on there.

**Comment by eliassal** [comment] 2023-02-13 19:57
I know very well kubectl and I did login to the ACR
`az acr login --name myregistry`
Then
`az aks get-credentials --resource-group y-RG --namemyAKSCluster`
then I was able to run
`kubectl get nodes`
and got

![image](https://user-images.githubusercontent.com/8447864/218561143-b6cfb63b-44aa-4841-9327-78503f228a98.png)

Then I executed the 3 statements

kubectl create -f k8s-namespace.yaml
kubectl apply -f sa-role.yaml
kubectl create -f k8s-Azure.yaml

but as you can notice in my initial post, it has the image pull error.

**Comment by xiaomi7732** [comment] 2023-02-24 17:53
Please see comments in #339. Let's address that first.

**Comment by xiaomi7732** [comment] 2023-04-04 23:43
The code in code light up works. There's no action to take for a code fix. I'll close this one for now. It seems like the issue is about missing permission to pull images from the registry.

**Closed by xiaomi7732** 2023-04-04 23:43 UTC
Labels: troubleshoot, external
